# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 03:40
from __future__ import unicode_literals

import detect.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiment', '0005_auto_20161008_1521'),
        ('usersystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=detect.models._face_upload_path_)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('recg_time', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceDetectReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_image', models.ImageField(upload_to=detect.models._face_upload_path_)),
                ('result_image', models.ImageField(null=True, upload_to=detect.models._face_upload_path_)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='recognizing', max_length=32)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='experiment.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_model', models.FileField(auto_created=True, upload_to=detect.models._model_upload_path_)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='untrained', max_length=32)),
                ('exp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trained', to='experiment.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='facedata',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='detect.FaceDetectReport'),
        ),
        migrations.AddField(
            model_name='facedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='usersystem.UserBaseInfo'),
        ),
    ]
