# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 11:30
from __future__ import unicode_literals

import detect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedetectreport',
            name='origin_image',
            field=models.ImageField(upload_to=detect.models._exp_upload_path_),
        ),
        migrations.AlterField(
            model_name='facedetectreport',
            name='result_image',
            field=models.ImageField(null=True, upload_to=detect.models._exp_upload_path_),
        ),
    ]
