# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 06:37
from __future__ import unicode_literals

import detect.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20161125_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='exp',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, related_name='trained', to='experiment.Experiment'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='face_model',
            field=models.FileField(null=True, upload_to=detect.models._model_upload_path_),
        ),
    ]
