# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0004_facedata_confident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='recg_time',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
